settings:
  APP_DISPLAY_NAME: SalemX
  PRODUCTION_APP_NAME: SalemX
  APP_GROUP_IDENTIFIER: group.kz.salemx.msg
  BASE_BUNDLE_IDENTIFIER: kz.salemx.msg
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 83LGSC2QPV
